/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package padraoNovo;

import bean.VendedorEfb;
import dao.VendedorDao_efb;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import tools.Util;

/**
 *
 * @author SERVER
 */
public class JDlgVendedorIA extends javax.swing.JDialog {

    /**
     * Creates new form JDlgVendedorNovo
     */
    boolean incluindo;
    MaskFormatter mascaracpf, mascararg;
    Util util;
    JDlgPesquisaVendedorNovo jDlgPesquisaVendedorNovo;
    VendedorDao_efb vendedorDao_efb;
    VendedorEfb vendedorEfb;

    public JDlgVendedorIA(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Vendedor");
        vendedorDao_efb = new VendedorDao_efb();
        vendedorEfb = new VendedorEfb();

        incluindo = false;
        try {
            mascaracpf = new MaskFormatter("###.###.###-##");
            mascararg = new MaskFormatter("#.###.###");
        } catch (ParseException ex) {
            Logger.getLogger(JDlgVendedorIA.class.getName()).log(Level.SEVERE, null, ex);
        }
        jFmtRg_efb.setFormatterFactory(new DefaultFormatterFactory(mascararg));
        jFmtCpf_efb.setFormatterFactory(new DefaultFormatterFactory(mascaracpf));
    }

    public void limpar() {
        util.limparCampos(jTxtCodigoVendedor_efb,
                jTxtNome_efb,
                jFmtCpf_efb,
                jChbAtivo_efb,
                jTxtEndereco_efb,
                jTxtSobrenome_efb,
                jFmtRg_efb);

    }

    public void Ativar(boolean ativar) {
        jTxtCodigoVendedor_efb.setEnabled(ativar);
    }

    public void setTelaAnterior(JDlgPesquisaVendedorNovo jDlgPesquisaVendedorNovo) {
        jDlgPesquisaVendedorNovo = jDlgPesquisaVendedorNovo;
    }

    public void beanView(VendedorEfb vendedor) {
        jTxtCodigoVendedor_efb.setText(String.valueOf(vendedor.getIdvendedorEfb()));
        jTxtNome_efb.setText(vendedor.getNomeEfb());
        jTxtSobrenome_efb.setText(vendedor.getSobrenomeEfb());
        jFmtCpf_efb.setText(vendedor.getCpfEfb());
        jFmtRg_efb.setText(vendedor.getRgEfb());
        jTxtEndereco_efb.setText(vendedor.getEnderecoEfb());
        jChbAtivo_efb.setSelected("Sim".equals(vendedor.getAtivoEfb()));
    }

    public VendedorEfb viewBean() {
        vendedorEfb.setIdvendedorEfb(Integer.parseInt(jTxtCodigoVendedor_efb.getText()));
        vendedorEfb.setNomeEfb(jTxtNome_efb.getText());
        vendedorEfb.setSobrenomeEfb(jTxtSobrenome_efb.getText());
        vendedorEfb.setCpfEfb(jFmtCpf_efb.getText());
        vendedorEfb.setRgEfb(jFmtRg_efb.getText());
        vendedorEfb.setEnderecoEfb(jTxtEndereco_efb.getText());
        vendedorEfb.setAtivoEfb(jChbAtivo_efb.isSelected() ? "Sim" : "Não");
        return vendedorEfb;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTxtCodigoVendedor_efb = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTxtNome_efb = new javax.swing.JTextField();
        jTxtEndereco_efb = new javax.swing.JTextField();
        jTxtSobrenome_efb = new javax.swing.JTextField();
        jChbAtivo_efb = new javax.swing.JCheckBox();
        jFmtCpf_efb = new javax.swing.JFormattedTextField();
        jFmtRg_efb = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        jBtnConfirmar_efb = new javax.swing.JButton();
        jBtnCancelar_efb = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Código Vendedor");

        jLabel2.setText("Nome");

        jLabel3.setText("CPF");

        jLabel4.setText("Endereço");

        jLabel5.setText("Sobrenome:");

        jLabel6.setText("Rg:");

        jChbAtivo_efb.setText(" Ativo");

        jBtnConfirmar_efb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/confirmar.png"))); // NOI18N
        jBtnConfirmar_efb.setText("Confirmar");
        jBtnConfirmar_efb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmar_efbActionPerformed(evt);
            }
        });

        jBtnCancelar_efb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        jBtnCancelar_efb.setText("Cancelar");
        jBtnCancelar_efb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelar_efbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(325, 325, 325)
                .addComponent(jBtnConfirmar_efb, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnCancelar_efb)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jBtnCancelar_efb)
                .addComponent(jBtnConfirmar_efb))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTxtNome_efb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                                .addComponent(jTxtCodigoVendedor_efb, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel3)
                            .addComponent(jFmtCpf_efb, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jTxtSobrenome_efb)
                            .addComponent(jLabel4)
                            .addComponent(jTxtEndereco_efb)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jFmtRg_efb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jChbAtivo_efb)
                        .addGap(311, 311, 311))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(12, 12, 12))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtCodigoVendedor_efb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(1, 1, 1)
                                .addComponent(jTxtNome_efb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtSobrenome_efb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtEndereco_efb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFmtCpf_efb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(4, 4, 4)
                .addComponent(jLabel6)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmtRg_efb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChbAtivo_efb))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnConfirmar_efbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmar_efbActionPerformed
        // TODO add your handling code here:
        if (getTitle().equals("Incluindo")) {
            vendedorEfb = viewBean();
            vendedorDao_efb.insert(vendedorEfb);
            util.mensagem("Incluindo");
            setVisible(false);
        } else if (getTitle().equals("Alterando")) {
            vendedorDao_efb.update(vendedorEfb);
            util.mensagem("Alterando");
            jTxtCodigoVendedor_efb.setEnabled(false);
            setVisible(false);
        } else {
            util.mensagem("ERRO");
        }
    }//GEN-LAST:event_jBtnConfirmar_efbActionPerformed

    private void jBtnCancelar_efbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelar_efbActionPerformed
        // TODO add your handling code here:
        util.mensagem("Cancelado");
        setVisible(false);
        limpar();
    }//GEN-LAST:event_jBtnCancelar_efbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgVendedorIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgVendedorIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgVendedorIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgVendedorIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgVendedorIA dialog = new JDlgVendedorIA(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancelar_efb;
    private javax.swing.JButton jBtnConfirmar_efb;
    private javax.swing.JCheckBox jChbAtivo_efb;
    private javax.swing.JFormattedTextField jFmtCpf_efb;
    private javax.swing.JFormattedTextField jFmtRg_efb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTxtCodigoVendedor_efb;
    private javax.swing.JTextField jTxtEndereco_efb;
    private javax.swing.JTextField jTxtNome_efb;
    private javax.swing.JTextField jTxtSobrenome_efb;
    // End of variables declaration//GEN-END:variables
}
